### ISSUE TITLE
How to use this extension?

### ISSUE THREAD

**Issue by sfili81** [davidhirtz/yii2-shopify#6]
Hi, i've followed your read.me file but it isn't clear how to use this extension into a real project.... how can i access to the relative views? for example to create a product and send it to shopify? how i can access to the frontend view? I'm using advance yii project... can you point me to the correct direction?

**Comment by davidhirtz** [comment]
Hi @sfili81, unfortunately I don't provide support for public usage of this repository. This package is part of both public and private repositories for dependant closed-source projects. I'm sorry.

**Comment by sfili81** [comment]
So it is useless..... i think if it is public a read.me file must contain at least how to install and basic configuration....
